In [ ]:
import numpy as np

In [ ]:
import pandas as pd

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('/content/real_estate_price_size.csv')

In [ ]:
df

price     size
0   234314.144   643.09
1   228581.528   656.22
2   281626.336   487.29
3   401255.608  1504.75
4   458674.256  1275.46
..         ...      ...
95  252460.400   549.80
96  310522.592  1037.44
97  383635.568  1504.75
98  225145.248   648.29
99  274922.856   705.29

[100 rows x 2 columns]

In [ ]:
df.head(2)

price    size
0  234314.144  643.09
1  228581.528  656.22

In [ ]:
df.tail(3)

price     size
97  383635.568  1504.75
98  225145.248   648.29
99  274922.856   705.29

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   price   100 non-null    float64
 1   size    100 non-null    float64
dtypes: float64(2)
memory usage: 1.7 KB


In [ ]:
df.shape

(100, 2)

In [ ]:
df.describe()

price         size
count     100.000000   100.000000
mean   292289.470160   853.024200
std     77051.727525   297.941951
min    154282.128000   479.750000
25%    234280.148000   643.330000
50%    280590.716000   696.405000
75%    335723.696000  1029.322500
max    500681.128000  1842.510000

In [ ]:
df.isnull().sum()

price    0
size     0
dtype: int64

In [ ]:
x=df.drop(['price'],axis=1)
y=df['price']

In [ ]:
x_copy=x.values.reshape(x.values.size,1)
x_copy.shape

(100, 1)

In [ ]:
x

size
0    643.09
1    656.22
2    487.29
3   1504.75
4   1275.46
..      ...
95   549.80
96  1037.44
97  1504.75
98   648.29
99   705.29

[100 rows x 1 columns]

In [ ]:
y

0     234314.144
1     228581.528
2     281626.336
3     401255.608
4     458674.256
         ...    
95    252460.400
96    310522.592
97    383635.568
98    225145.248
99    274922.856
Name: price, Length: 100, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x_copy,y,test_size=0.25,random_state=95)

In [ ]:
x_train

array([[ 643.09],
       [1032.06],
       [ 827.84],
       [ 685.48],
       [1183.46],
       [ 643.09],
       [ 681.07],
       [ 681.07],
       [1188.62],
       [ 569.17],
       [1009.25],
       [ 685.48],
       [1334.1 ],
       [ 633.19],
       [ 823.21],
       [1009.25],
       [1122.34],
       [1275.46],
       [1103.3 ],
       [ 698.29],
       [1508.84],
       [ 727.88],
       [1236.93],
       [1283.85],
       [ 633.19],
       [ 525.81],
       [ 647.5 ],
       [1496.36],
       [ 681.07],
       [1021.95],
       [ 525.81],
       [1021.95],
       [ 622.97],
       [ 682.26],
       [ 518.38],
       [ 597.9 ],
       [1496.36],
       [ 647.5 ],
       [1021.95],
       [ 705.29],
       [1504.75],
       [ 570.25],
       [1334.1 ],
       [1300.96],
       [ 617.05],
       [ 694.52],
       [ 570.89],
       [1334.1 ],
       [ 685.48],
       [ 682.26],
       [ 681.07],
       [ 694.52],
       [ 857.54],
       [1010.33],
       [ 694.52],
       [15

In [ ]:
x_test

array([[ 601.66],
       [ 694.52],
       [ 656.22],
       [ 828.16],
       [ 549.8 ],
       [ 570.89],
       [ 698.29],
       [ 643.41],
       [1060.36],
       [ 549.69],
       [ 549.8 ],
       [ 648.29],
       [ 690.54],
       [1021.95],
       [ 681.07],
       [ 656.22],
       [ 827.09],
       [1379.72],
       [1009.25],
       [1021.95],
       [ 685.48],
       [ 685.48],
       [ 698.5 ],
       [1060.36],
       [ 685.48]])

In [ ]:
y_train

83    282683.544
56    320345.520
58    330677.128
75    286161.600
76    382120.152
         ...    
5     245050.280
62    359674.440
19    299416.976
41    217468.224
22    412569.472
Name: price, Length: 75, dtype: float64

In [ ]:
y_test

88    211904.536
9     218630.608
1     228581.528
60    251188.824
95    252460.400
26    271793.312
45    300061.480
71    181587.576
44    293044.496
21    171795.240
73    211724.096
98    225145.248
16    248337.600
40    310045.712
28    297760.440
72    298926.496
65    304587.272
15    440201.616
13    418753.008
70    276875.632
84    303597.216
38    292965.216
61    263311.696
10    279555.096
74    228313.024
Name: price, dtype: float64

In [ ]:
from sklearn.linear_model import LinearRegression
cat=LinearRegression()
cat.fit(x_train,y_train)


LinearRegression()

In [ ]:
cat.predict([[300]])

array([169227.88705584])

In [ ]:
cat.predict([[1000],[500]])

array([325683.1228951 , 213929.38300991])